server:
  port: 8090
  error:
    include-exception: false
    include-stacktrace: never # ?? ??? stacktrace ??? ??? ? ??

spring:
  profiles:
    group:
      "local": "local,common"
      "dev": "dev,common"
      "prod": "prod,common"

---
# ?? ?? ??
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/rest-server
    username: root
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #show_sql: true # ??? ??? ??
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.H2Dialect

    open-in-view: false # OSIV ??

---
# ?? ??
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/dpcms
    username: root
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        #show_sql: true # ??? ??? ??
        format_sql: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.H2Dialect

    open-in-view: false # OSIV ??

---
# ??
spring:
  config:
    activate:
      on-profile: "common"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  devtools:
    restart:
      enabled: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging.level:
  org.hibernate.SQL: debug # ??? ??

#  org.hibernate.type: trace #??? ?? 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #??? ?? 3.x, hibernate6


jwt:
  secret-key: 'fa5e2d1c7e68b4173f7099a756a243d2b84e3a3d1c4b6f0ed9e4bebf4682d22e'
  refresh-token-expiration-millis: 300000
  access-token-expiration-millis: 60000






